# Generated by Django 3.0.3 on 2020-04-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0002_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='name',
        ),
    ]
