# Generated by Django 3.2.3 on 2021-08-17 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0004_add_users_auth_token_if_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollout',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
