# Generated by Django 3.2.3 on 2021-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0006_userdetail_manager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='enable_timesheet_auto_send',
            field=models.BooleanField(default=False),
        ),
    ]
